export const FETCH_PAYMENT_SUCCESS = 'FETCH_PAYMENT_SUCCESS';
export const FETCH_PAYMENT_FAILURE = 'FETCH_PAYMENT_FAILURE';
export const FETCH_PAYMENT_CREATE_SUCCESS = 'FETCH_PAYMENT_CREATE_SUCCESS';
export const FETCH_PAYMENT_CREATE_FAILURE = 'FETCH_PAYMENT_CREATE_FAILURE';