export const FETCH_HOME_CHECK_SUCCESS = 'FETCH_HOME_CHECK_SUCCESS';
export const FETCH_HOME_CHECK_FAILURE = 'FETCH_HOME_CHECK_FAILURE';
export const FETCH_HOME_PROGRESS_SUCCESS = 'FETCH_HOME_PROGRESS_SUCCESS';
export const FETCH_HOME_PROGRESS_FAILURE = 'FETCH_HOME_PROGRESS_FAILURE';