// redux/actions/types.js

export const FETCH_INFOADMIN_SUCCESS = 'FETCH_INFOADMIN_SUCCESS';
export const FETCH_INFOADMIN_FAILURE = 'FETCH_INFOADMIN_FAILURE';


export const FETCH_INFOUSER_SUCCESS = 'FETCH_INFOUSER_SUCCESS';
export const FETCH_INFOUSER_FAILURE = 'FETCH_INFOUSER_FAILURE';